jobs:
  pull-request:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BODY: Bump version
        PULL_REQUEST_TITLE: Release ${{ github.ref }}
      name: pull-request-action
      uses: vsoch/pull-request-action@master
name: Release Pull Request
on:
  repository_dispatch:
    types: trigger-ga___release-pull-request.yaml
