jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create Release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: ${{ contains(github.ref, 'RC') }}
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
